---
- name: Install imagemagick and dependencies
  pacman:
    state: present
    name:
      - feh
      - imagemagick
      - libpng
      - libraw
      - librsvg
      - openjpeg2
      - scrot
  tags:
    - imagemagick

- name: Install GIMP
  pacman:
    state: present
    name:
      - gimp
      - gimp-plugin-gmic
  tags:
    - gimp

- name: Install vlc
  pacman:
    state: present
    name:
      - vlc
