---
- name: Install android-tools
  aur:
    name:
        - android-tools
        - android-udev
    state: present

- name: Add {{ user.name }} to adbusers group
  user:
      name: "{{ user.name }}"
      groups: adbusers
      append: yes
