---
- name: Install LibreOffice
  aur:
    name:
        - libreoffice-fresh
        - sublime-text-dev
    state: present

- name: Install calibre
  aur:
    name: calibre
    state: present

- name: Install pandoc and dependencies
  aur:
    name:
      - pandoc
      - pandoc-citeproc
    state: present

- name: Install latex
  aur:
    name:
      - texlive-bin
      - texlive-core
      - texlive-latexextra
      - texlive-most
    state: present

- name: Install qalculate
  aur:
    name: qalculate-gtk
    state: present

- name: Install zathura
  aur:
    name:
      - zathura
      - zathura-pdf-mupdf
      - evince
    state: present

- name: hardlink zathura config
  file:
    src: /home/{{ user.name }}/{{ dotfiles.destination }}/zathura/zathurarc
    path: /home/{{ user.name }}/.config//zathura/zathurarc
    state: hard
  when: dotfiles is defined
