---
- name: Install Firefox
  pacman:
    name:
        - firefox
        - flashplugin
    state: present
  tags:
    - firefox

- name: Install Chromium
  pacman:
    name: chromium
    state: present
  tags:
    - chromium

- name: Install tor-browser
  aur:
    name:
        - tor
        - tor-browser
        - torsocks
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - tor-browser
    - aur
