---
- name: Install Firefox
  aur:
    name:
        - firefox
        - flashplugin
    state: present

- name: Install Chromium
  aur:
    name: chromium
    state: present

- name: Install tor-browser
  aur:
    name:
        - tor
        - tor-browser
        - torsocks
    user: "{{ user.name }}"
    skip_pgp: yes
