---
- name: Install VirtualBox and dependencies
  pacman:
    name:
      - net-tools
      - virtualbox
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso
      - virtualbox-guest-utils
      - linux-headers
    state: present

- name: Install VirtualBox extensions
  aur: name=virtualbox-ext-oracle user={{ user.name }}
  tags:
    - aur

- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes
  tags:
    - user

- name: Install docker
  pacman:
    state: present
    name:
      - docker
      - docker-compose
      - docker-machine

- name: Enable and start docker socket
  service: name=docker.socket enabled=yes state=started
