---
- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - sudo
    - user

- name: Copy sudo configuration
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  tags:
    - sudo

- name: Use all cores when compressing packages
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: "^COMPRESSXZ"
    line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Copy pacman configuration file
  copy:
    src=pacman.conf
    dest=/etc/pacman.conf

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks
        state=directory
  tags:
    - packages

- name: full system upgrade
  pacman:
      update_cache: yes
      upgrade: yes

- name: Set the hostname
  hostname:
    name: {{ hostname }}
  when: hostname is defined

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set local en_US.UTF-8 locale systemwide
  copy:
    dest: "/etc/locale.conf"
    content: "LANG=en_US.UTF-8"

- name: set timezone to Europe/Rome
  timezone:
    name: Europe/Rome

- name: Install Power management
  pacman:
    state: present
    name:
      - acpid
      - acpi
      - powertop
  tags:
    - power

- name: Enable ACPID
  service: name=acpid.service enabled=yes
  tags:
    - power

- name: Enable fstrim for ssd
  service: name=fstrim.timer enabled=yes

- name: Install Intel microcode
  pacman: name=intel-ucode state=present
  when: '"GenuineIntel" in ansible_processor'

- name: Install universal base packages
  pacman:
    state: present
    name:
      - binutils
      - python
      - rsync
      - tree
      - mlocate
      - htop
  tags:
    - packages

- name: Install editors
  pacman:
    state: present
    name: "{{ editors }}"

- name: Install shells
  include_tasks: shell.yml
